<?php
/**
 *-----------------------------------
 * @Author: Wang Ya Hua
 * @Email : 13146042502@163.com
 * @Time  : 2017/12/17  22:01
 * @File  : CustomerController.php
 * @Description :
 *-----------------------------------
 */
namespace app\admin\controller;

use cmf\controller\AdminBaseController;
use think\Db;
use think\Validate;

class CustomerController extends AdminBaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        echo 1;die;
    }
}