<?php
/**
 *-----------------------------------
 * @Author: Wang Ya Hua
 * @Email : 13146042502@163.com
 * @Time  : 2017/12/17  22:01
 * @File  : CustomerController.php
 * @Description :
 *-----------------------------------
 */
namespace app\admin\controller;

use app\admin\model\CustomerModel;
use cmf\controller\AdminBaseController;
use think\Db;
use think\Validate;

class CustomerController extends AdminBaseController
{

    public $CustomerModel = '';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->CustomerModel = new CustomerModel();
    }

    public function getUserList()
    {
        $user_list = db('user')->field('id,user_login,user_nickname')->where('user_type = 1')->select()->toArray();
        return $user_list;
    }

    public function index()
    {
        $user_list = $this->getUserList();
        $this->assign("user_list", $user_list);
        return $this->fetch();
    }

    public function getDataList()
    {
        $params = input('get.');
        $data = $this->CustomerModel->getDataList($params);
        $count = $this->CustomerModel->getDataCount($params);
        AdminBaseController::jsonTableData($data,$count);
    }

    public function add()
    {
        if ($this->request->isPost() && $this->request->isAjax()) {
            $this->submitAdd();
        }
        $user_list = $this->getUserList();
        $this->assign("user_list", $user_list);
        return $this->fetch();
    }

    /**
     * 添加操作
     */
    protected function submitAdd()
    {
        $postData = input('post.');
        $rule = [
            'name'  => 'require',
            'user_name'  => 'require',
            'mobile' => 'require',
            'invoice_header' => 'require',
            'taxpayer_number'=> 'require',
            'finance_address'=> 'require'
        ];
        $msg = [
            'name.require' => '客户名称不为空',
            'user_name.require'   => '姓名不为空',
            'mobile.require'  => '手机不为空',
            'invoice_header.require'  => '发票抬头为不为空',
            'taxpayer_number.require' => '纳税人识别号',
            'finance_address.require' => '财务信息地址不为空'
        ];
        $validate = new Validate($rule, $msg);
        if(!$validate->check($postData)){
            $this->error($validate->getError());
        }
        $data = array(
            'customer' => array(
                'name'          => $postData['name'],
                'user_name'     => $postData['user_name'],
                'mobile'        => $postData['mobile'],
                'address'       => $postData['address']
            ),
            'finance' => array(
                'invoice_header'   => $postData['invoice_header'],
                'taxpayer_number'  => $postData['taxpayer_number'],
                'address'          => $postData['finance_address'],
                'mobile'           => $postData['finance_mobile'],
                'account_open_bank'=> $postData['account_open_bank'],
                'bank_account'     => $postData['bank_account'],
                'customer_manager' => $postData['customer_manager'],
                'customer_type'    => $postData['customer_type'],
                'intergral_num'    => $postData['intergral_num'],
                'remarks'          => $postData['remarks']
            )
        );
        $result = $this->CustomerModel->addData($data);
        if($result){
            $this->success('添加成功');
        }else{
            $this->error('添加失败，请稍候再试');
        }
    }
}